export enum ACTIONS_TYPES {
    GET_EVENTS = 'GET_EVENTS',
    GET_EVENTS_SUCCEED = 'GET_EVENTS_SUCCEED',

    POST_EVENT = 'POST_EVENT',
    POST_EVENT_SUCCEED = 'POST_EVENT_SUCCEED',

    PUT_EVENT = 'PUT_EVENT',
    PUT_EVENT_SUCCEED = 'PUT_EVENT_SUCCEED',
}

export enum VISIBILITY {
    FRIENDS,
    FRIENDS_FRIENDS,
    ALL,
}
