export enum ACTIONS_TYPES {
    POST_NEW_PARTICIPANT = 'POST_NEW_PARTICIPANT',
    POST_NEW_PARTICIPANT_SUCCEED = 'POST_NEW_PARTICIPANT_SUCCEED',

    POST_PARTICIPANT = 'POST_PARTICIPANT',
    POST_PARTICIPANT_SUCCEED = 'POST_PARTICIPANT_SUCCEED',

    REMOVE_NEW_PARTICIPANT = 'REMOVE_NEW_PARTICIPANT',
    REMOVE_NEW_PARTICIPANT_SUCCEED = 'REMOVE_NEW_PARTICIPANT_SUCCEED',

    REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT',
    REMOVE_PARTICIPANT_SUCCEED = 'REMOVE_PARTICIPANT_SUCCEED',
}
