export enum ACTIONS_TYPES {
    GET_GUIDES = 'GET_GUIDES',
    GET_GUIDES_SUCCEED = 'GET_GUIDES_SUCCEED',

    POST_GUIDE = 'POST_GUIDE',
    POST_GUIDE_SUCCEED = 'POST_GUIDE_SUCCEED',

    POST_GUIDE_LIKE = 'POST_GUIDE_LIKE',
    POST_GUIDE_LIKE_SUCCEED = 'POST_GUIDE_LIKE_SUCCEED',
}

export enum TAGS {
    GAAAAY = 'GAAAAY',
    KEKENOID = 'KEKENOID',
    HELISEXUAL = 'HELISEXUAL',
}
