export enum ACTIONS_TYPES {
    GET_TRAVELS = 'GET_TRAVELS',
    GET_TRAVELS_SUCCEED = 'GET_TRAVELS_SUCCEED',

    POST_TRAVEL = 'POST_TRAVEL',
    POST_TRAVEL_SUCCEED = 'POST_TRAVEL_SUCCEED',

    PUT_TRAVEL = 'PUT_TRAVEL',
    PUT_TRAVEL_SUCCEED = 'PUT_TRAVEL_SUCCEED',
}

export enum VISIBILITY {
    FRIENDS,
    FRIENDS_FRIENDS,
    ALL,
}
